Repository Nexters/BRUNO, pull requests merged in 2022-02, with the labels that each got.

#8 Add CreateCookie markup
  src/App.tsx
  src/assets/styles/global.ts
  src/components/shared/MainButton/MainButton.tsx
  src/components/shared/PageLayout/PageLayout.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/CreateCookiePage/index.ts
  src/pages/CreateCookiePage/styled.tsx
Labels: markup

#10 Header와 Navigation 추가
  src/App.tsx
  src/assets/Icon/24px-edit.svg
  src/assets/Icon/index.ts
  src/components/Header/Header.tsx
  src/components/Header/index.ts
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/index.ts
  src/components/shared/IconButton/IconButton.tsx
  src/components/shared/IconButton/index.ts
  src/components/shared/PageLayout/PageLayout.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/indes.ts
  src/routes/Main.tsx
Labels: markup

#11 UserHome markup
  src/App.tsx
  src/assets/styles/global.ts
  src/assets/styles/theme.ts
  src/components/LoginForm/LoginForm.tsx
  src/components/RequestContent/RequestContent.tsx
  src/components/RequestContent/RequestItem.tsx
  src/components/RequestContent/ResponseButton.tsx
  src/components/RequestContent/index.ts
  src/components/UserContent/UserContent.tsx
  src/components/UserContent/index.ts
  src/components/UserHomeTab/TabItem.tsx
  src/components/UserHomeTab/UserHomeTab.tsx
  src/components/UserHomeTab/index.ts
  src/components/UserHomeTab/types.ts
  src/components/UserPhoto/UserPhoto.tsx
  src/components/UserPhoto/index.ts
  src/components/UserProfile/BioSection.tsx
  src/components/UserProfile/UserProfile.tsx
  src/components/UserProfile/index.ts
  src/components/shared/MainButton/MainButton.tsx
  src/components/shared/MainButton/index.ts
  src/components/shared/PageLayout/PageLayout.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/CreateCookiePage/styled.tsx
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/index.ts
  src/routes/User.tsx
Labels: markup

#12 Home Feed 마크업
  src/assets/Icon/24px-hammer.svg
  src/assets/Icon/24px-view.svg
  src/assets/Icon/ArrowElbowDownRight.svg
  src/assets/Icon/index.ts
  src/assets/fonts/SansitaSwashed.woff2
  src/assets/fonts/index.ts
  src/assets/images/index.tsx
  src/assets/images/nft/Default_01.png
  src/assets/images/nft/Default_02.png
  src/assets/images/nft/Default_03.png
  src/assets/images/profile/Default_01.png
  src/assets/images/profile/Default_02.png
  src/assets/images/profile/Default_03.png
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedContent.tsx
  src/components/Feed/UserInfo.tsx
  src/components/Feed/index.ts
  src/components/Feed/type.ts
  src/components/Header/Header.tsx
  src/components/HomeTab/HomeTab.tsx
  src/components/HomeTab/const.ts
  src/components/HomeTab/index.ts
  src/components/Navigation/Navigation.tsx
  src/components/shared/CategoryButton/CategoryButton.tsx
  src/components/shared/CategoryButton/index.ts
  src/fonts.d.ts
  src/index.tsx
  src/pages/HomePage/HomePage.tsx
  tsconfig.json
Labels: markup

#13 style: 💄 Home page 디자인 디테일 수정
  src/assets/styles/theme.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedContent.tsx
  src/components/Header/Header.tsx
  src/components/HomeTab/HomeTab.tsx
  src/pages/HomePage/HomePage.tsx
Labels: markup

#14 쿠키 생성 페이지 마크업 수정
  src/App.tsx
  src/components/HomeTab/HomeTab.tsx
  src/components/Navigation/Navigation.tsx
  src/components/shared/const.ts
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/CreateCookiePage/const.ts
  src/pages/CreateCookiePage/styled.tsx
  src/routes/Main.tsx
Labels: markup

#16 Klip QR code 로그인 연동
  package.json
  src/App.tsx
  src/components/shared/PageLayout/PageLayout.tsx
  src/klip/axios.ts
  src/klip/index.ts
  src/klip/types.ts
  src/klip/useKlipLogin.ts
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/JoinPage/JoinPage.tsx
  src/pages/JoinPage/index.ts
  src/pages/KlipLoginPage/index.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/OtherWalletLoginPage/OtherWalletLoginPage.tsx
  src/pages/OtherWalletLoginPage/index.ts
  src/recoil/auth/atoms.ts
  src/recoil/auth/index.ts
  src/recoil/auth/selectors.ts
  src/routes/Auth.tsx
  src/utils/web2app.js
  yarn.lock
Labels: auth, klip

#17 web2app deeplink 로직 & auth protect routes 추가
  .eslintrc.js
  package.json
  src/App.tsx
  src/components/shared/MainButton/MainButton.tsx
  src/components/shared/PageLayout/PageLayout.tsx
  src/hooks/index.ts
  src/hooks/useLogin.ts
  src/klip/useKlipLogin.ts
  src/pages/LoginPage/LoginPage.tsx
  src/routes/Auth.tsx
  src/routes/PrivateRoute.tsx
  yarn.lock
Labels: auth, klip

#18 cookie detail page
  src/assets/styles/mixin.ts
  src/assets/styles/theme.ts
  src/components/CookieInfo/CookieInfo.tsx
  src/components/CookieInfo/index.ts
  src/components/CookieInfo/styled.tsx
  src/components/Feed/index.ts
  src/components/FeedCard/FeedCard.tsx
  src/components/FeedCard/FeedContent.tsx
  src/components/FeedCard/UserInfo.tsx
  src/components/FeedCard/index.ts
  src/components/FeedCard/type.ts
  src/components/LoginForm/LoginForm.tsx
  src/components/Navigation/Navigation.tsx
  src/components/shared/PageLayout/PageLayout.tsx
  src/pages/CookieDetailPage/CookieDetailPage.tsx
  src/pages/CookieDetailPage/index.ts
  src/pages/CookieDetailPage/types.ts
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/CreateCookiePage/styled.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/JoinPage/JoinPage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/routes/Auth.tsx
  src/routes/Main.tsx
Labels: markup, review반영

#20 유저 홈 내 받은 요청 스타일 수정
  src/components/RequestContent/RequestContent.tsx
  src/components/RequestContent/RequestItem.tsx
  src/components/RequestContent/ResponseButton.tsx
Labels: markup

#19 Modal 컴포넌트 추가
  src/assets/styles/theme.ts
  src/components/RequestContent/RequestContent.tsx
  src/components/RequestContent/RequestItem.tsx
  src/components/RequestContent/ResponseButton.tsx
  src/components/UserPhoto/index.ts
  src/components/UserProfile/UserPhoto.tsx
  src/components/UserProfile/UserProfile.tsx
  src/components/shared/Modal/Modal.tsx
  src/components/shared/Modal/index.ts
  src/components/shared/Modal/styled.tsx
Labels: markup

#21 모바일 웹 로그인 플로우 수정
  src/App.tsx
  src/assets/images/index.tsx
  src/assets/images/logo/Main_01.png
  src/assets/styles/global.ts
  src/assets/styles/theme.ts
  src/components/Header/Header.tsx
  src/components/shared/Modal/Modal.tsx
  src/components/shared/Modal/index.ts
  src/klip/useKlipLogin.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/const.ts
  src/pages/LoginPage/styled.tsx
  src/pages/LoginPage/types.ts
  src/pages/UserPage/UserPage.tsx
  src/routes/Auth.tsx
Labels: markup

#23 create cookie 페이지 - input, textArea 컴포넌트화
  src/assets/styles/theme.ts
  src/components/shared/CategoryButton/CategoryButton.tsx
  src/components/shared/Input/Input.tsx
  src/components/shared/Input/index.ts
  src/components/shared/MainButton/MainButton.tsx
  src/components/shared/TextArea/TextArea.tsx
  src/components/shared/TextArea/index.ts
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/CreateCookiePage/const.ts
  src/pages/CreateCookiePage/styled.tsx
Labels: markup

#28 쿠키 가격 수정페이지 마크업
  src/components/shared/CategoryButton/CategoryButton.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/CreateCookiePage/const.ts
  src/routes/Main.tsx
Labels: markup

#29 Regist ID 페이지 마크업 수정
  src/components/Header/const.ts
  src/components/LoginForm/LoginForm.tsx
  src/components/LoginForm/const.ts
  src/components/shared/Input/Input.tsx
  src/components/shared/PageLayout/PageLayout.tsx
  src/components/shared/TextArea/TextArea.tsx
  src/pages/AskPage/AskPage.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/JoinPage/JoinPage.tsx
Labels: markup

#30 Regist Info 페이지 구현
  src/components/LoginForm/index.ts
  src/components/RegistId/RegistId.tsx
  src/components/RegistId/const.ts
  src/components/RegistId/index.ts
  src/components/RegistId/type.ts
  src/components/RegisterInfo/RegisterInfo.tsx
  src/components/RegisterInfo/const.ts
  src/components/RegisterInfo/index.ts
  src/pages/JoinPage/JoinPage.tsx
Labels: markup

#34 feat: 🎸 Select category 화면 구현
  src/assets/Icon/Icon.tsx
  src/assets/styles/global.ts
  src/components/RegisterInfo/RegisterInfo.tsx
  src/components/SelectCategory/CategoryButton.tsx
  src/components/SelectCategory/SelectCategory.tsx
  src/components/SelectCategory/const.ts
  src/components/SelectCategory/index.ts
  src/pages/JoinPage/JoinPage.tsx
Labels: markup

#36 fetch categories
  .eslintrc.js
  .prettierrc
  src/App.tsx
  src/assets/styles/theme.ts
  src/components/HomeTab/HomeTab.tsx
  src/components/HomeTab/const.ts
  src/components/shared/CategoryButton/CategoryButton.tsx
  src/components/shared/CategoryButton/const.ts
  src/components/shared/const.ts
  src/config/axios.ts
  src/config/dev.config.ts
  src/config/real.config.ts
  src/pages/AskPage/AskPage.tsx
  src/pages/CookieDetailPage/CookieDetailPage.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/queries/categories.ts
  src/queries/cookies.ts
  src/recoil/category/atoms.ts
  src/recoil/category/index.ts
  src/recoil/category/selectors.ts
  src/recoil/category/types.ts
Labels: offchain

#39 all cookies api
  package.json
  src/App.tsx
  src/components/FeedCard/FeedCard.tsx
  src/components/FeedCard/FeedContent.tsx
  src/components/FeedCard/UserInfo.tsx
  src/components/FeedCard/type.ts
  src/components/Navigation/Navigation.tsx
  src/pages/CookieDetailPage/CookieDetailPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/queries/cookies.ts
  src/queries/types.ts
  src/utils/format.ts
  yarn.lock
Labels: offchain

#37 Create Cookie contract
  package.json
  src/App.tsx
  src/assets/Icon/Icon.tsx
  src/assets/abi/cookie.js
  src/components/CategorySection/CategorySection.tsx
  src/components/CategorySection/index.ts
  src/components/shared/Modal/styled.tsx
  src/components/shared/QRcodeModal/QRcodeModal.tsx
  src/components/shared/QRcodeModal/index.ts
  src/components/shared/QRcodeModal/styled.tsx
  src/components/shared/QRcodeModal/useQRcodeModal.tsx
  src/klip/abi.js
  src/klip/const.ts
  src/klip/execute.js
  src/klip/getParams.ts
  src/klip/index.ts
  src/klip/types.ts
  src/klip/useKlipLogin.ts
  src/klip/utils.ts
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/CreateCookiePage/const.ts
  src/pages/CreateCookiePage/index.ts
  src/pages/CreateCookiePage/types.ts
  src/pages/LoginPage/LoginPage.tsx
  src/queries/cookies.ts
  src/queries/utils.ts
  src/recoil/klip/atoms.ts
  src/recoil/klip/index.ts
  src/recoil/klip/selectors.ts
  src/recoil/ui/atoms.ts
  src/recoil/ui/index.ts
  yarn.lock
Labels: onchain, klip

#40 get Cookie Details
  src/components/CookieDetails/CookieDetails.tsx
  src/components/CookieDetails/index.ts
  src/components/CookieDetails/styled.tsx
  src/components/CookieHistorySection/CookieHistorySection.tsx
  src/components/CookieHistorySection/index.ts
  src/components/CookieHistorySection/styled.tsx
  src/components/CookieInfo/index.ts
  src/components/FeedCard/FeedContent.tsx
  src/hooks/useLogin.ts
  src/pages/CookieDetailPage/CookieDetailPage.tsx
  src/pages/CookieDetailPage/index.ts
  src/pages/CookieDetailPage/types.ts
  src/pages/HomePage/HomePage.tsx
  src/queries/cookies.ts
  src/queries/hooks.ts
  src/queries/types.ts
  src/queries/utils.ts
  src/recoil/category/selectors.ts
  src/routes/Main.tsx
Labels: offchain

#43 on boarding 페이지 마크업
  src/App.tsx
  src/components/Header/SubHeader.tsx
  src/components/Header/const.ts
  src/components/RegistId/RegistId.tsx
  src/components/RegisterInfo/RegisterInfo.tsx
  src/components/SelectCategory/SelectCategory.tsx
  src/components/shared/PageLayout/PageLayout.tsx
  src/pages/CompletedMakePage/CompletedMakePage.tsx
  src/pages/CompletedMakePage/const.ts
  src/pages/CompletedMakePage/index.ts
  src/pages/JoinPage/JoinPage.tsx
  src/pages/TutorialPage/TutorialPage.tsx
  src/pages/TutorialPage/const.ts
  src/pages/TutorialPage/index.ts
  src/routes/Tutorial.tsx
Labels: markup

#41 UserPage 구현 (ask 데이터 제외)
  src/assets/Icon/Icon.tsx
  src/assets/Icon/box-blue.svg
  src/assets/Icon/box-lime.svg
  src/assets/Icon/close-blue.svg
  src/assets/Icon/close-lime.svg
  src/assets/Icon/close-pink.svg
  src/assets/Icon/close-purple.svg
  src/assets/Icon/cookie-blue.svg
  src/assets/Icon/cookie-lime.svg
  src/assets/Icon/cookie-pink.svg
  src/assets/Icon/cookie-purple.svg
  src/assets/Icon/index.ts
  src/assets/images/profile/Default_01.png
  src/assets/images/profile/Default_02.png
  src/components/CategorySection/CategorySection.tsx
  src/components/CollectedCookieGrid/CollectedCookie.tsx
  src/components/CollectedCookieGrid/CollectedCookieGrid.tsx
  src/components/CollectedCookieGrid/index.ts
  src/components/CookieGrid/CookieGrid.tsx
  src/components/CookieGrid/CookieItem.tsx
  src/components/CookieGrid/const.ts
  src/components/CookieGrid/index.ts
  src/components/FeedCard/FeedCard.tsx
  src/components/FeedCard/UserInfo.tsx
  src/components/HomeTab/HomeTab.tsx
  src/components/HomeTab/const.ts
  src/components/Navigation/Navigation.tsx
  src/components/UserContent/UserContent.tsx
  src/components/UserHomeTab/UserHomeTab.tsx
  src/components/UserProfile/BioSection.tsx
  src/components/UserProfile/UserPhoto.tsx
  src/components/UserProfile/UserProfile.tsx
  src/components/shared/CategoryButton/CategoryButton.tsx
  src/components/shared/CategoryButton/const.ts
  src/pages/AskPage/AskPage.tsx
  src/pages/CookieDetailPage/CookieDetailPage.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/JoinPage/JoinPage.tsx
  src/pages/UserPage/UserPage.tsx
  src/queries/cookies.ts
  src/queries/hooks.ts
  src/queries/types.ts
  src/queries/users.ts
  src/recoil/category/atoms.ts
  src/recoil/category/index.ts
  src/recoil/category/selectors.ts
  src/recoil/category/types.ts
Labels: offchain

#44 get cookies by category
  src/assets/images/index.tsx
  src/assets/images/nft/Cookie_Blue.png
  src/assets/images/nft/Cookie_Lime.png
  src/assets/images/nft/Cookie_Pink.png
  src/assets/images/nft/Cookie_Purple.png
  src/assets/styles/theme.ts
  src/components/CookieDetails/CookieDetails.tsx
  src/components/CookieGrid/CookieGrid.tsx
  src/components/CookieGrid/CookieItem.tsx
  src/components/FeedCard/FeedCard.tsx
  src/components/FeedCard/FeedContent.tsx
  src/components/FeedCard/type.ts
  src/components/shared/NFTCookie/NFTCookie.tsx
  src/components/shared/NFTCookie/index.ts
  src/pages/CreateCookiePage/const.ts
  src/pages/HomePage/HomePage.tsx
  src/queries/cookies.ts
  src/queries/hooks.ts
Labels: offchain

#47 Ask API 연동 (조회/삭제)
  src/components/AskContent/AskContent.tsx
  src/components/AskContent/AskItem.tsx
  src/components/AskContent/ResponseButton.tsx
  src/components/AskContent/index.ts
  src/components/CookieDetails/CookieDetails.tsx
  src/components/FeedCard/FeedCard.tsx
  src/components/FeedCard/FeedContent.tsx
  src/components/Navigation/Navigation.tsx
  src/components/RequestContent/RequestContent.tsx
  src/components/RequestContent/index.ts
  src/components/UserContent/UserContent.tsx
  src/components/UserHomeTab/UserHomeTab.tsx
  src/components/UserProfile/UserPhoto.tsx
  src/config/dev.config.ts
  src/config/real.config.ts
  src/hooks/useLogin.ts
  src/pages/AskPage/AskPage.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/NotFoundPage/index.ts
  src/pages/UserPage/UserPage.tsx
  src/queries/ask.ts
  src/queries/hooks.ts
  src/queries/types.ts
  src/queries/users.ts
  src/recoil/category/selectors.ts
  src/routes/Main.tsx
  src/routes/User.tsx
Labels: offchain

#48 PR : Settings 지갑 연동 구현
  src/assets/Icon/cookiepang_logo.svg
  src/assets/Icon/index.ts
  src/assets/Icon/qr-1.svg
  src/assets/Icon/qr-2.svg
  src/assets/Icon/qr-3.svg
  src/assets/styles/global.ts
  src/components/CookieDetails/CookieDetails.tsx
  src/components/CookieHistorySection/CookieHistorySection.tsx
  src/components/FeedCard/FeedCard.tsx
  src/components/FeedCard/FeedContent.tsx
  src/components/Header/MainHeader.tsx
  src/components/Header/SubHeader.tsx
  src/components/Header/const.ts
  src/components/shared/MainButton/MainButton.tsx
  src/components/shared/Modal/Modal.tsx
  src/components/shared/PageLayout/PageLayout.tsx
  src/components/shared/QRcodeModal/QRcodeModal.tsx
  src/components/shared/QRcodeModal/styled.tsx
  src/components/shared/QRcodeModal/useQRcodeModal.tsx
  src/hooks/useLogin.ts
  src/klip/abi.js
  src/klip/axios.ts
  src/klip/execute.js
  src/klip/getParams.ts
  src/klip/mintCookie.ts
  src/klip/types.ts
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/CreateCookiePage/const.ts
  src/pages/SettingPage/SettingsPage.tsx
  src/pages/SettingPage/const.ts
  src/pages/SettingPage/index.ts
  src/queries/cookies.ts
  src/queries/hooks.ts
  src/queries/types.ts
  src/recoil/category/selectors.ts
  src/recoil/klip/atoms.ts
  src/routes/Main.tsx
Labels: markup, onchain, offchain

#57 PR : implement buyCookie
  src/components/CookieDetails/CookieDetails.tsx
  src/components/CookieDetails/const.ts
  src/components/Header/MainHeader.tsx
  src/klip/axios.ts
  src/klip/buyCookie.ts
  src/klip/const.ts
  src/klip/execute.js
  src/klip/mintCookie.ts
  src/pages/AskPage/AskPage.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/queries/ask.ts
  src/queries/cookies.ts
  src/queries/types.ts
  src/recoil/klip/atoms.ts
Labels: onchain, offchain

#58 register api 연동
  src/assets/images/index.tsx
  src/assets/images/logo/Main_01.png
  src/assets/images/logo/main.png
  src/components/RegistId/RegistId.tsx
  src/components/RegistId/const.ts
  src/components/RegisterInfo/RegisterInfo.tsx
  src/components/RegisterInfo/const.ts
  src/components/SelectCategory/SelectCategory.tsx
  src/components/SelectCategory/const.ts
  src/components/shared/Input/Input.tsx
  src/hooks/useLogin.ts
  src/klip/axios.ts
  src/klip/useKlipLogin.ts
  src/pages/AskPage/AskPage.tsx
  src/pages/CreateCookiePage/CreateCookiePage.tsx
  src/pages/JoinPage/JoinPage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/styled.tsx
  src/queries/categories.ts
  src/queries/cookies.ts
  src/queries/types.ts
  src/queries/users.ts
  src/recoil/user/atoms.ts
  src/recoil/user/index.ts
  src/routes/Auth.tsx
Labels: offchain
